pii-classified-country: GBR

mastercard:
  api:
    environment:
      base-path: https://sandbox.api.mastercard.com/installments  # Refers to sandbox endpoint
    authentication:
      key-file:  # Copy .p12 file in src/main/resources and set value as classpath:nameOfYourP12File.p12
      consumer-key: # Copy the Consumer key from "Sandbox/Production Keys" section on your project page
      keystore-alias: # Alias of your key. Default key alias for sandbox is keyalias
      keystore-password: # Password of your Keystore. Default keystore password for sandbox project is keystorepassword
    encryption:
      key-file: #Copy client encryption .pem file in src/main/resources and set value as classpath:nameOfYourClientEncryptionPemFile.pem
    decryption:
      key-file: #Copy mastercard encryption .p12 file in src/main/resources and set value as classpath:nameOfYourMastercardtEncryptionP12File.p12
      keystore-alias: # Alias of your key.
      keystore-password: # Password of your Keystore.